//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalTesting.PayPalAlpha {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mercurypay.com", ConfigurationName="PayPalAlpha.mobileSoap")]
    public interface mobileSoap {
        
        // CODEGEN: Generating message contract since element name tran from namespace http://www.mercurypay.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/MobileTransactionPilot", ReplyAction="*")]
        PayPalTesting.PayPalAlpha.MobileTransactionPilotResponse MobileTransactionPilot(PayPalTesting.PayPalAlpha.MobileTransactionPilotRequest request);
        
        // CODEGEN: Generating message contract since element name tran from namespace http://www.mercurypay.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditTransactionPilot", ReplyAction="*")]
        PayPalTesting.PayPalAlpha.CreditTransactionPilotResponse CreditTransactionPilot(PayPalTesting.PayPalAlpha.CreditTransactionPilotRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MobileTransactionPilotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MobileTransactionPilot", Namespace="http://www.mercurypay.com", Order=0)]
        public PayPalTesting.PayPalAlpha.MobileTransactionPilotRequestBody Body;
        
        public MobileTransactionPilotRequest() {
        }
        
        public MobileTransactionPilotRequest(PayPalTesting.PayPalAlpha.MobileTransactionPilotRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mercurypay.com")]
    public partial class MobileTransactionPilotRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tran;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pw;
        
        public MobileTransactionPilotRequestBody() {
        }
        
        public MobileTransactionPilotRequestBody(string tran, string pw) {
            this.tran = tran;
            this.pw = pw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MobileTransactionPilotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MobileTransactionPilotResponse", Namespace="http://www.mercurypay.com", Order=0)]
        public PayPalTesting.PayPalAlpha.MobileTransactionPilotResponseBody Body;
        
        public MobileTransactionPilotResponse() {
        }
        
        public MobileTransactionPilotResponse(PayPalTesting.PayPalAlpha.MobileTransactionPilotResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mercurypay.com")]
    public partial class MobileTransactionPilotResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MobileTransactionPilotResult;
        
        public MobileTransactionPilotResponseBody() {
        }
        
        public MobileTransactionPilotResponseBody(string MobileTransactionPilotResult) {
            this.MobileTransactionPilotResult = MobileTransactionPilotResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditTransactionPilotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreditTransactionPilot", Namespace="http://www.mercurypay.com", Order=0)]
        public PayPalTesting.PayPalAlpha.CreditTransactionPilotRequestBody Body;
        
        public CreditTransactionPilotRequest() {
        }
        
        public CreditTransactionPilotRequest(PayPalTesting.PayPalAlpha.CreditTransactionPilotRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mercurypay.com")]
    public partial class CreditTransactionPilotRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tran;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pw;
        
        public CreditTransactionPilotRequestBody() {
        }
        
        public CreditTransactionPilotRequestBody(string tran, string pw) {
            this.tran = tran;
            this.pw = pw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditTransactionPilotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreditTransactionPilotResponse", Namespace="http://www.mercurypay.com", Order=0)]
        public PayPalTesting.PayPalAlpha.CreditTransactionPilotResponseBody Body;
        
        public CreditTransactionPilotResponse() {
        }
        
        public CreditTransactionPilotResponse(PayPalTesting.PayPalAlpha.CreditTransactionPilotResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mercurypay.com")]
    public partial class CreditTransactionPilotResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreditTransactionPilotResult;
        
        public CreditTransactionPilotResponseBody() {
        }
        
        public CreditTransactionPilotResponseBody(string CreditTransactionPilotResult) {
            this.CreditTransactionPilotResult = CreditTransactionPilotResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mobileSoapChannel : PayPalTesting.PayPalAlpha.mobileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mobileSoapClient : System.ServiceModel.ClientBase<PayPalTesting.PayPalAlpha.mobileSoap>, PayPalTesting.PayPalAlpha.mobileSoap {
        
        public mobileSoapClient() {
        }
        
        public mobileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mobileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mobileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mobileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PayPalTesting.PayPalAlpha.MobileTransactionPilotResponse PayPalTesting.PayPalAlpha.mobileSoap.MobileTransactionPilot(PayPalTesting.PayPalAlpha.MobileTransactionPilotRequest request) {
            return base.Channel.MobileTransactionPilot(request);
        }
        
        public string MobileTransactionPilot(string tran, string pw) {
            PayPalTesting.PayPalAlpha.MobileTransactionPilotRequest inValue = new PayPalTesting.PayPalAlpha.MobileTransactionPilotRequest();
            inValue.Body = new PayPalTesting.PayPalAlpha.MobileTransactionPilotRequestBody();
            inValue.Body.tran = tran;
            inValue.Body.pw = pw;
            PayPalTesting.PayPalAlpha.MobileTransactionPilotResponse retVal = ((PayPalTesting.PayPalAlpha.mobileSoap)(this)).MobileTransactionPilot(inValue);
            return retVal.Body.MobileTransactionPilotResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PayPalTesting.PayPalAlpha.CreditTransactionPilotResponse PayPalTesting.PayPalAlpha.mobileSoap.CreditTransactionPilot(PayPalTesting.PayPalAlpha.CreditTransactionPilotRequest request) {
            return base.Channel.CreditTransactionPilot(request);
        }
        
        public string CreditTransactionPilot(string tran, string pw) {
            PayPalTesting.PayPalAlpha.CreditTransactionPilotRequest inValue = new PayPalTesting.PayPalAlpha.CreditTransactionPilotRequest();
            inValue.Body = new PayPalTesting.PayPalAlpha.CreditTransactionPilotRequestBody();
            inValue.Body.tran = tran;
            inValue.Body.pw = pw;
            PayPalTesting.PayPalAlpha.CreditTransactionPilotResponse retVal = ((PayPalTesting.PayPalAlpha.mobileSoap)(this)).CreditTransactionPilot(inValue);
            return retVal.Body.CreditTransactionPilotResult;
        }
    }
}
